### ISSUE TITLE
Update Node.js 16 → 02 Obsolete warning

### ISSUE THREAD

**Issue by leotsarev** [shine1594/secrets-to-env-action#1]
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: shine1594/secrets-to-env-action@v1.6.1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

P.S. Thank you for this nice action!

**Comment by shine1594** [comment]
The runtime has been set to Node 20 and applied in version 1.7.0.
